name: Deploy backend

on:
  push:
    branches: [ "CICD" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Publish
      run: |
        dotnet publish -o publish -c Release --self-contained false -r linux-x64

    - name: Inject secrets into appsettings.json
      run: |
        FILE=publish/appsettings.json
        sed -i "s|__Google_Secret__|${{ secrets.Google_Secret }}|g" $FILE
        sed -i "s|__Github_Secret__|${{ secrets.Gthub_Secret }}|g" $FILE

    - name: Copy to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "publish/"
        target: "/var/www/backend/new"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          ACTIVE=$(grep -oE '127\.0\.0\.1:500[12]' /etc/nginx/sites-available/backend.conf | head -n1 | grep -o '500[12]')

          if [ "$ACTIVE" = "5001" ]; then
            TARGET=green
            PORT=5002
            OLD=blue
          else
            TARGET=blue
            PORT=5001
            OLD=green
          fi

          sudo rsync -a --delete /var/www/backend/new/publish/ /var/www/backend/$TARGET/

          sudo systemctl start backend-$TARGET

          HEALTH_OK=false

            for i in {1..15}; do
                if curl -fs http://127.0.0.1:$PORT/api/health/status > /dev/null; then
                    HEALTH_OK=true
                    break
                fi
                sleep 2
            done

          sudo sed -i -E "s/(127\.0\.0\.1:)$ACTIVE/\1$PORT/" /etc/nginx/sites-available/backend.conf
          sudo nginx -t
          sudo nginx -s reload

          sleep 5
          sudo systemctl stop backend-$OLD
